# Generated by Django 6.0.8 on 2026-08-08 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelUser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['fecha_limite'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='descripcion',
            new_name='notas',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='apellidos',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='tipo',
            new_name='tipo_contacto',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_programada',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='empresa_o_institucion',
        ),
        migrations.AddField(
            model_name='actividad',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_limite',
            field=models.DateField(default='2026-08-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='resumen',
            field=models.CharField(default='Sin resumen', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.CharField(choices=[('Entrevista', 'Entrevista'), ('Llamada', 'Llamada'), ('Reunión', 'Reunión'), ('Correo', 'Correo'), ('Seguimiento', 'Seguimiento')], default='Llamada', max_length=50),
        ),
        migrations.AddField(
            model_name='contacto',
            name='carrera_rubro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
