# Generated by Django 6.0.8 on 2026-08-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelUser', '0002_alter_actividad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='contactos_archivos/'),
        ),
    ]
