# Generated by Django 6.0.8 on 2026-08-09 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelUser', '0003_contacto_activo_contacto_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_asignadas', to='PanelUser.contacto'),
        ),
    ]
