# Generated by Django 6.0.8 on 2026-08-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelUser', '0004_alter_actividad_asignado_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='asignado_a',
        ),
        migrations.AddField(
            model_name='actividad',
            name='asignado_a',
            field=models.ManyToManyField(blank=True, related_name='actividades_asignadas', to='PanelUser.contacto'),
        ),
    ]
