# Generated by Django 6.0.8 on 2026-08-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelUser', '0005_remove_actividad_asignado_a_actividad_asignado_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.CharField(choices=[('Entrevista', 'Entrevista'), ('Llamada', 'Llamada'), ('Reunión', 'Reunión'), ('Correo', 'Correo'), ('Seguimiento', 'Seguimiento'), ('Convocatoria', 'Convocatoria'), ('Presentación / Pitch', 'Presentación / Pitch'), ('Otro', 'Otro')], default='Llamada', max_length=50),
        ),
    ]
