# Generated by Django 6.0.8 on 2026-08-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelUser', '0006_alter_actividad_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='contactos_archivos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='PanelUser.contacto')),
            ],
            options={
                'verbose_name': 'Archivo de Contacto',
                'verbose_name_plural': 'Archivos de Contactos',
                'ordering': ['creado_en'],
            },
        ),
    ]
