# Generated by Django 6.0.8 on 2026-08-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(choices=[('investigacion_insights', 'Investigación e Insights'), ('tecnologia_informacion', 'Tecnología de la Información'), ('recursos_humanos', 'Recursos Humanos'), ('arte_digital', 'Arte Digital'), ('media_audiovisual', 'Media Audiovisual')], max_length=100, unique=True),
        ),
    ]
