# Generated by Django 6.0.8 on 2026-08-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_remove_area_tipo_alter_area_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, choices=[('investigacion_insights', 'Investigación e Insights'), ('tecnologia_informacion', 'Tecnología de la Información'), ('recursos_humanos', 'Recursos Humanos'), ('arte_digital', 'Arte Digital'), ('media_audiovisual', 'Media Audiovisual')], default='', max_length=50),
        ),
    ]
