# Generated by Django 6.0.8 on 2026-08-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_alter_usuario_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nombre'], 'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
    ]
