# Generated by Django 6.0.8 on 2026-08-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_alter_area_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='area',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin_crm', 'Administrador de CRM'), ('panel_user', 'Usuario del Panel')], max_length=25),
        ),
    ]
